image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test

pylint:
  stage: Static Analysis
  allow_failure: false
  script:
  - pylint src/*.py
  - flake8 src/*.py --statistics --count

pytest:
  stage: Test
  script:
  - pytest

