WINDOW_WIDTH = 800 # in pixel
WINDOW_LENGTH = 800
READ_DATA_MIN_VALUE = -10
READ_DATA_MAX_VALUE = 10
READ_DATA_SAMPLE_RATE = 5000 # in Hz
READ_SAMPLE_PER_WINDOW_REFRESH = 100
WINDOW_REFRESH_TIME = 10 # in ms
